export const ADD_STUDENTS="ADD_STUDENTS";
export const UPDATE_STUDENTs="UPDATE_STUDENTS";
export const DELETE_STUDENTS="DELETE_STUDENTS";
export const GET_ALLSTUDENTS="GET_ALLSTUDENTS";
export const GET_STUDENTBYID="GET_STUDENTBYID";
